// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwqeyeqjpxtumnriijef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3cWV5ZXFqcHh0dW1ucmlpamVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTExNDIsImV4cCI6MjA3MTE4NzE0Mn0.f4uy2wvSyO7j3RnrUFMcaKOasv3tQRJNqnVE7saXNnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});